### ISSUE TITLE
编辑文章报错

### ISSUE THREAD

**Issue by TIANLI0** [am-abudu/Qexo#1]
在编辑文章时报错
```
报错信息： 404 {"message"： "Not Found"， "documentation_url"： "https://docs.github.com/rest/reference/repos#get-repository-content"}
```
查看的请求地址为https://xxx.vercel.app/edit.html?file=undefined

注 配置无误 编辑页面可以正常使用

**Comment by am-abudu** [comment]
请问是文件名为undefined吗，编辑界面是否可以获取到文件内容

**Comment by TIANLI0** [comment]
> 请问是文件名为undefined吗，编辑界面是否可以获取到文件内容

看吧https://user-images.githubusercontent.com/52097638/142747392-4f64bb51-b82a-418f-8a11-ad6337e15b78.mp4

**Comment by am-abudu** [comment]
这些文章都不行吗，尝试清除缓存？

**Comment by TIANLI0** [comment]
> 这些文章都不行吗，尝试清除缓存？

怪事
报错
```
AssertionError("Cache object can't be deleted because its id attribute is set to None.",)
```

**Comment by am-abudu** [comment]
> > 这些文章都不行吗，尝试清除缓存？
> 
> 怪事 报错
> 
> ```
> AssertionError("Cache object can't be deleted because its id attribute is set to None.",)
> ```

你是否曾使用过0.01或0.1版本...这两个版本存在id保存的问题，你可能需要重新创建一个MongoDB数据库

**Comment by TIANLI0** [comment]
> > > 这些文章都不行吗，尝试清除缓存？
> > 
> > 怪事 报错
> > 
> > ```
> > AssertionError("Cache object can't be deleted because its id attribute is set to None.",)
> > ```
> 
> 你是否曾使用过0.01或0.1版本...这两个版本存在id保存的问题，你可能需要重新创建一个MongoDB数据库

确实用过

**Comment by am-abudu** [comment]
这两个版本有严重问题，你可能需要重新创建一个MongoDB数据库并重新部署以解决该问题

**Comment by sgr997** [comment]
我的有些文章也会报这个错，Qexo是今天刚搭建部署的，mongoDB也是今天创建的。
- Qexo版本：1.4.2
- Hexo版本：5.4.0
![image](https://user-images.githubusercontent.com/51942582/146386246-62f7e974-11ca-4ee8-9d7d-868786c409df.png)

**Comment by am-abudu** [comment]
> 我的有些文章也会报这个错，Qexo是今天刚搭建部署的，mongoDB也是今天创建的。
> 
> * Qexo版本：1.4.2
> * Hexo版本：5.4.0
>   ![image](https://user-images.githubusercontent.com/51942582/146386246-62f7e974-11ca-4ee8-9d7d-868786c409df.png)

尝试清除缓存 若还是如此就Q我吧
