### ISSUE TITLE
友链嵌入异常(vlts)

### ISSUE THREAD

**Issue by qystudio0** [am-abudu/Qexo#103]
### Qexo 版本

v1.5.5

### 问题描述

嵌入vlts的友链显示异常

### 复现链接

复现方式
```
<div class="friends-group"><div id="friend-content" class="friend-content"></div></div>
<link rel="stylesheet" href="https://npm.elemecdn.com/qexo-static@1.0.7/hexo/friends/friends.css"/>
<script src="https://cdn.jsdelivr.net/gh/Fgaoxing/blog-cdn@main/source/js/friends.js"></script>
<script>loadQexoFriends("friend-content", "https://setting.qystudio.ltd")</script>
```

### 截图

![20220228_202323](https://user-images.githubusercontent.com/78479629/155983025-3cda9944-71b0-4315-91e1-884711fadff5.png)

**Comment by am-abudu** [comment]
这个文件的友链并非由我维护 请联系@Fgaoxing

**Comment by yuanyuanshan0627** [comment]
我想请问一下SITE是我 qexo 的地址吗
<img width="1425" alt="image" src="https://github.com/Qexo/Qexo/assets/119478320/78a3bf34-d0eb-48d0-81f1-7d14a284ad37">
是这个吗
