### ISSUE TITLE
what is it?

### ISSUE THREAD

**Issue by SUNWUYUAN** [am-abudu/Qexo#107]
### Qexo 版本

Default version of vercel deployment

### 问题描述

I used the deployment of vercel, and then prompted an error. I tried it several times（I can't speak English. This paragraph is translated by translation software. Sorry）

This is all the tips of vercel：

Cloning github.com/SUNWUYUAN/hexoblog (Branch: main, Commit: acaf788)
Cloning completed: 524.822ms
Analyzing source code...
Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
Installing build runtime...
Build runtime installed: 2.836s
Installing build runtime...
Build runtime installed: 6.502s
Looking up build cache...
Build Cache not found
Collecting asgiref==3.4.1
  Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting autopep8==1.5.7
  Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
Collecting beautifulsoup4==4.10.0
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 6.6 MB/s eta 0:00:00
Collecting boto==2.49.0
  Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 36.3 MB/s eta 0:00:00
  Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 KB 28.4 MB/s eta 0:00:00
Collecting botocore==1.23.23
  Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 92.5 MB/s eta 0:00:00
Collecting certifi==2021.5.30
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 35.2 MB/s eta 0:00:00
Collecting cffi==1.15.0
  Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 KB 57.9 MB/s eta 0:00:00
Collecting charset-normalizer==2.0.4
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting click==8.0.1
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 22.8 MB/s eta 0:00:00
Collecting colorama==0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting Deprecated==1.2.13
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting dj-database-url==0.5.0
  Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting Django==3.0.5
  Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 101.0 MB/s eta 0:00:00
Collecting djongo==1.3.6
  Downloading djongo-1.3.6.tar.gz (331 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 KB 58.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting django-cors-headers==3.10.1
Collecting dnspython==1.16.0
  Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 KB 38.2 MB/s eta 0:00:00
Collecting gunicorn==20.1.0
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 18.4 MB/s eta 0:00:00
Collecting idna==3.2
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 KB 13.6 MB/s eta 0:00:00
Collecting jmespath==0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting prettytable==2.2.0
  Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
Collecting pyasn1==0.4.8
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pycodestyle==2.7.0
  Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 9.9 MB/s eta 0:00:00
Collecting pycparser==2.21
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 26.4 MB/s eta 0:00:00
Collecting PyGithub==1.55
  Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 KB 45.7 MB/s eta 0:00:00
Collecting PyJWT==2.3.0
  Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
Collecting pymongo==3.12.0
  Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 KB 60.7 MB/s eta 0:00:00
Collecting PyNaCl==1.4.0
  Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 KB 85.0 MB/s eta 0:00:00
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 49.4 MB/s eta 0:00:00
Collecting python-decouple==3.4
  Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
Collecting pytz==2021.1
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 KB 69.0 MB/s eta 0:00:00
Collecting requests==2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting rsa==4.7.2
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting s3transfer==0.5.0
  Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 KB 21.2 MB/s eta 0:00:00
Collecting six==1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting soupsieve==2.2.1
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting sqlparse==0.2.4
  Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
Collecting tcping==0.1.1rc1
  Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
  Preparing metadata (setup.py): finished with status 'done'
Collecting toml==0.10.2
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting ujson==4.1.0
  Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 KB 40.3 MB/s eta 0:00:00
Collecting Unipath==1.1
  Downloading Unipath-1.1.tar.gz (30 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting urllib3==1.26.7
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 KB 33.3 MB/s eta 0:00:00
Collecting wcwidth==0.2.5
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting whitenoise==5.3.0
  Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
Collecting wrapt==1.13.3
  Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
Collecting Markdown==3.3.6
  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 23.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-4.11.2-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
  Running setup.py install for Unipath: started
  Running setup.py install for Unipath: finished with status 'done'
  Running setup.py install for tcping: started
  Running setup.py install for tcping: finished with status 'done'
  Running setup.py install for djongo: started
  Running setup.py install for djongo: finished with status 'done'
Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 idna-3.2 importlib-metadata-4.11.2 jmespath-0.10.0 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 requests-2.26.0 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/vercel/path1/manage.py", line 22, in <module>
    main()
  File "/vercel/path1/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/vercel/path1/core/settings.py", line 80, in <module>
    ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DOMAINS'
Traceback (most recent call last):
  File "/vercel/path1/manage.py", line 22, in <module>
    main()
  File "/vercel/path1/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/vercel/path1/core/settings.py", line 80, in <module>
    ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DOMAINS'
Error: Command "./migrate.sh" exited with 1

### 截图

![Uploading 屏幕截图 2022-03-12 115829.jpg…]()

**Comment by mis1042** [comment]
Try to redeploy.If the problem persists please reply

**Comment by mis1042** [comment]
or check your environment variables

**Comment by mis1042** [comment]
@am-abudu 来解决问题（

**Comment by Fgaoxing** [comment]
If you are Chinese, you can speak Chinese

**Comment by am-abudu** [comment]
now this application is not supported international languages without Chinese. so if you want to use it, you may wait me adding English or other languages support  (may be a long time)

**Comment by Fgaoxing** [comment]
@am-abudu 他好像是个中国人！

**Comment by SUNWUYUAN** [comment]
> @am-abudu他是个中国人！

你猜对了

**Comment by SUNWUYUAN** [comment]
> Try to redeploy.If the problem persists please reply

我重试了很多次，都是这样

**Comment by SUNWUYUAN** [comment]
> > Try to redeploy.If the problem persists please reply
> 
> 我重试了很多次，都是这样

也许是我运气不好

**Comment by SUNWUYUAN** [comment]
习惯性的翻译成英文。

**Comment by SUNWUYUAN** [comment]
> pls try to add your environment variables "DOMAINS" and test then
> 
> now this application is not supported international languages without Chinese. so if you want to use it, you may wait me adding English or other languages support (may be a long time)

我并没有找到添加这个的方法，我是在vercel上部署的，唉唉唉唉唉唉唉无语😑

**Comment by am-abudu** [comment]
> > pls try to add your environment variables "DOMAINS" and test then
> > now this application is not supported international languages without Chinese. so if you want to use it, you may wait me adding English or other languages support (may be a long time)
> 
> 我并没有找到添加这个的方法，我是在vercel上部署的，唉唉唉唉唉唉唉无语😑

请先查看Wiki

**Comment by SUNWUYUAN** [comment]
> pls try to add your environment variables "DOMAINS" and test then
> 
> now this application is not supported international languages without Chinese. so if you want to use it, you may wait me adding English or other languages support (may be a long time)

《两个中国人用翻译软件在github上聊天的故事》

**Comment by SUNWUYUAN** [comment]
> > > pls try to add your environment variables "DOMAINS" and test then
> > > now this application is not supported international languages without Chinese. so if you want to use it, you may wait me adding English or other languages support (may be a long time)
> > 
> > 
> > 我并没有找到添加这个的方法，我是在vercel上部署的，唉唉唉唉唉唉唉无语😑
> 
> 请先查看Wiki

 vercel的第1次部署就是这样子的，wiki看了几遍，没有发现帮助的东西啊，抱歉。也许是运气问题？您可以再试一下vercel部署吗？您那里部署正常吗？

**Comment by Fgaoxing** [comment]
@SUNWUYUAN 部署正常！

**Comment by am-abudu** [comment]
@SUNWUYUAN 请截图环境变量列表页面

**Comment by SUNWUYUAN** [comment]
> @SUNWUYUAN 请截图环境变量列表页面

额(⊙﹏⊙)，我想我这好像部署好了，貌似是环境变量得问题，麻烦您了，谢谢，再见

**Comment by oxarlly** [comment]
为什么我按照教程来反复修改反复检查还是出现下面报错：
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _ 
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
 /_/    \_\____/ \____|\____|\____|
当前环境: Vercel / Linux / Qexo 3.5.4 / Python 3.9.8 / django.db.backends.postgresql
No changes detected
ERROR:root:Language获取失败, 默认为zh_CN
ERROR:root:获取PROVIDER时出错: 跳过
           _               _ 
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _ 
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
