### ISSUE TITLE
文章列表不会自动更新

### ISSUE THREAD

**Issue by chiyuki0325** [am-abudu/Qexo#112]
### Qexo 版本

v1.5.5

### 问题描述

从主页「新文章」按钮新建的文章和通过 Hexo cli 新建的文章都不会添加到 Qexo 的文章列表中（文章列表的「新建文章」按钮未测试），在 MongoDB 的 hexoweb_cache 数据库中，相应的文章列表也没有更新。

这个 bug 可能与 MarkDown 源文件名和文章名字不一致有关。

希望改为在每天第一次登录 Qexo（或可以设定间隔）时强制更新一次文章列表数据库。

### 截图

这是 Qexo 的文章列表：
![Screenshot_20220315_235510_com huawei browser](https://user-images.githubusercontent.com/73830635/158418803-dddaba62-457f-4218-9084-486aec9036fc.jpg)

这是生成好的博客：
![Screenshot_20220315_235531](https://user-images.githubusercontent.com/73830635/158418912-98765207-6c46-4e7f-910f-1805d09ef480.jpg)

可以看出「new-domain.md」（“网站今日更换域名”）文章没有出现在 Qexo 文章列表中。

**Comment by Fgaoxing** [comment]
这应该是缓存的问题，可以手动清理

**Comment by am-abudu** [comment]
对此我已经给出了更棒的答案
请在设置中点击”一键设置Webhook“
