### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#13]
在：[https://www.yt-blog.top/%E5%BB%BA%E8%AE%AE/](建议)

**Comment by am-abudu** [comment]
1.空文章是指文件名为.md吗，此时理论上文章名为空，除了文章名其他会正常显示
2.说说有更棒的平台支持，qexo是一个hexo在线编辑器，理论上不应支持这些功能（若需要该功能见Hexoplusplus Artitalk）
3.由于框架问题缩小体积较难，不过后期会精简static目录
4.todo
5.todo
6.页面网址我记得是可以在文件头使用permarlink选项修改，故不会引入程序
7.链接前缀自己加吧。。


8.评论功能同样有更棒的选择，如valine waline artalk twikoo
9.登录功能要用来干什么，暂时没有找到应用场景

**Comment by Fgaoxing** [comment]
谢谢

**Comment by am-abudu** [comment]
登录要做成什么样的，登录、注册、查询登录状态接口？感觉必要性并不高

**Comment by Fgaoxing** [comment]
那onearager兼容呢？

**Comment by am-abudu** [comment]
你是指onemanager嘛 这个有啥兼容的地方呢 现在在做s3对象存储作为图床的功能
