### ISSUE TITLE
Vercel部署后初始化错误

### ISSUE THREAD

**Issue by Juaran** [am-abudu/Qexo#132]
### Qexo 版本

v1.62

### 问题描述

* 我已经详细阅读了部署文档并严格按照要求执行：[Vercel 部署](https://github.com/am-abudu/Qexo/wiki/Vercel-部署)
* 我已查找了所有issue内所有包含关键字**Vercel**的问题和回复，未发此类问题
* 我已尝试按照出错指引，但依旧未能解决问题

问题描述：
1. 我在Vercel部署完成时，进入[https://qexo-7069ueomh-XXX.vercel.app/init/](https://qexo-7069ueomh-xxx.vercel.app/init/)页面
2. 页面提示信息：欢迎！请点击开始以继续初始化
3. 点击“开始”后，页面在一段时间后返回错误（如截图所示）
4. 我尝试重新部署，三次均得到同样结果
5. 我检查了MongoDB数据集合，所有表字段已经建立，但没有写入数据

### 截图

<img src="https://transfer.sh/get/nVHwVv/Snipaste_2022-04-07_14-47-43.png">

**Comment by Juaran** [comment]
Oh sorry, 再次重新部署之后已经进入到用户配置界面了。大概率是Environment设置错误

**Comment by Juaran** [comment]
在完成hexo仓库配置后，图床设置点“跳过”或“下一步”都得到了同样的错误。检查MongoDB内已经存储了hexo仓库信息

**Comment by Fgaoxing** [comment]
@Juaran 你访问的是单次部署的域名吗？

**Comment by Fgaoxing** [comment]
@am-abudu

**Comment by Juaran** [comment]
@Fgaoxing @am-abudu 一直报这个函数超时错误，我晕！想是不是网络有问题，于是换了教程里推荐的MongoDB的地区（AWS / N. Virginia (us-east-1)），就没有报错了。之前MongoDB选的香港，我还以为能快一点(尴尬--。)
