### ISSUE TITLE
开放API接口

### ISSUE THREAD

**Issue by am-abudu** [am-abudu/Qexo#15]
基于API密钥开放API接口，不再仅限于Webhook事件

**Comment by CCKNBC** [comment]
@am-abudu 好的

**Comment by Fgaoxing** [comment]
@am-abudu 能用api，获取文章，和写入文章吗？

**Comment by Fgaoxing** [comment]
还有编辑主题

**Comment by Fgaoxing** [comment]
最好支持post/get

**Comment by am-abudu** [comment]
因为一些问题 这个功能不会在下一个版本实装 下一个版本主要是对s3对象存储的支持 @Fgaoxing

**Comment by Fgaoxing** [comment]
@am-abudu 能集成api图床吗？我没服务器建不了动态，你能利用GitHub api吗

**Comment by am-abudu** [comment]
> @am-abudu 能集成api图床吗？我没服务器建不了动态，你能利用GitHub api吗

很遗憾 不可以 这是违反github＆jsdelivr的tos都用法

**Comment by Fgaoxing** [comment]
那用https://console.leancloud.app/那？

**Comment by Fgaoxing** [comment]
那用：[https://console.leancloud.app/](https://console.leancloud.app/)呢？

**Comment by am-abudu** [comment]
> 那用：https://console.leancloud.app/呢？

已经提供了非常丰富的自定义功能，建议自行研究一下

**Comment by Fgaoxing** [comment]
那用onedrive和aliyun那？

**Comment by Fgaoxing** [comment]
求你了！

**Comment by Fgaoxing** [comment]
我都是一遍一遍部署vercel，太麻烦了，就是 [这样](https://img.yt-blog.top) ,目录是vercel里自带的！

**Comment by Fgaoxing** [comment]
![image](https://user-images.githubusercontent.com/92655031/146675171-ea1e1fa4-64f2-4a64-a2b4-a9fb31c8bae8.png)

**Comment by am-abudu** [comment]
> 我都是一遍一遍部署vercel，太麻烦了，就是 [这样](https://img.yt-blog.top) ,目录是vercel里自带的！

猜你需要：https://github.com/yumusb/autoPicCdn
<img width="416" alt="图片1" src="https://user-images.githubusercontent.com/51912589/146679726-60642ea7-66d9-4b70-9c02-252e848a7b5d.png">
https://chuibi.cn/

**Comment by am-abudu** [comment]
#20
