### ISSUE TITLE
更新后出现500错误

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#21]
1.4.4有问题
![image](https://user-images.githubusercontent.com/92655031/147242459-413f0546-00f1-464d-9221-06e5de2570c8.png)
来自 https://admin.yt-blog.top/

**Comment by Fgaoxing** [comment]
@am-abudu

**Comment by am-abudu** [comment]
请简要描述你操作的步骤

**Comment by Fgaoxing** [comment]
我直接替换文件上传的

**Comment by Fgaoxing** [comment]
https://github.com/Fgaoxing/qexo/settings

**Comment by Fgaoxing** [comment]
https://github.com/Fgaoxing/qexo/

**Comment by am-abudu** [comment]
登录后出现问题?尝试保留数据库环境变量重新部署

**Comment by Fgaoxing** [comment]
之前没有啊，我试试吧

**Comment by Fgaoxing** [comment]
还是不行
我重新部署了已经，要不我试试删掉项目，不过我要复习

**Comment by am-abudu** [comment]
> 还是不行 我重新部署了已经，要不我试试删掉项目，不过我要复习

尝试重新fork项目？

**Comment by Fgaoxing** [comment]
一键部署按钮，你加一个 [[](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)](https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)'[[](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)](https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)'

**Comment by Fgaoxing** [comment]
[[](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)](https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)

**Comment by Fgaoxing** [comment]
[![alt text][[](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e "title")](https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)

**Comment by Fgaoxing** [comment]
`[![alt text][(https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e "title")](https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)`

**Comment by Fgaoxing** [comment]
好了，谢谢

**Comment by Fgaoxing** [comment]
# Qexo
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)

一个快速、强大、漂亮的在线 Hexo 编辑器，您的 Star 是对我最大的支持。
![](https://user-images.githubusercontent.com/51912589/142183851-7428c3ef-8d38-4029-9ca4-0f5e0f3ccfc0.png)
## 特色功能
- 自定义图床上传图片
- 在线配置编辑
- 在线文章管理
- 在线页面管理
- 较为完善的缓存功能
- Webhook 清除缓存
- 自动检查更新
- 实验性的在线更新
- 自动填充date模板

## 如何部署
### 申请 MongoDB 
[注册 MongoDB 账号](https://www.mongodb.com/cloud/atlas/register) 创建免费 MongoDB 数据库，区域推荐选择 AWS / N. 
  Virginia (us-east-1) 在 Clusters 页面点击 CONNECT，按步骤设置允许所有 IP 地址的连接），创建数据库用户，并记录数据库连接信息，密码即为你所设置的值
![](https://user-images.githubusercontent.com/51912589/140946317-bafeac24-fe3f-408b-927a-ca9a88168fa8.png)
### Fork 本项目
打开 [项目主页](https://github.com/am-abudu/Qexo) 点击 Fork 将项目复刻到您的账户下
### 创建 Vercel 项目
打开 [Vercel](https://vercel.com) 注册账号并绑定 Github 新建一个项目并绑定 Fork 的仓库
### 部署
在项目部署界面添加环境变量 Environment Variables
| 名称 | 意义 | 示例 |
| --- | --- | --- |
| DOMAINS | 你所允许通信的安全域名 注意双引号 | [".vercel.app", "127.0.0.1", ".yoursite.com"] |
| MONGODB_HOST | MongoDB 连接地址 | mongodb+srv://cluster0.xxxx.mongodb.net |
| MONGODB_PORT | MongoDB 通信端口 默认应填写 27017 | 27017 |
| MONGODB_USER | MongoDB 用户名 | abudu |
| MONGODB_DB | MongoDB 数据库名 | Cluster0 |
| MONGODB_PASS | MongoDB 密码 | JWo0xxxxxxxx |

点击 Deploy 开始部署，若没有 Error 信息即可打开域名进入初始化引导
## 鸣谢
- [Ace](https://ace.c9.io/)
- [Argon-Dashboard-Django](https://github.com/creativetimofficial/argon-dashboard-django)
- [Bootstrap](https://getbootstrap.com/)
- [Bootstrap-Notify](https://github.com/mouse0270/bootstrap-notify)
- [Django](https://github.com/django/django)
- [Djongo](https://github.com/nesdis/djongo)
- [HexoPlusPlus](https://github.com/HexoPlusPlus/HexoPlusPlus)
- [jQuery](https://jquery.com/)
- [Vercel-Python-WSGI](https://github.com/ardnt/vercel-python-wsgi)
'`# Qexo
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)

一个快速、强大、漂亮的在线 Hexo 编辑器，您的 Star 是对我最大的支持。
![](https://user-images.githubusercontent.com/51912589/142183851-7428c3ef-8d38-4029-9ca4-0f5e0f3ccfc0.png)
## 特色功能
- 自定义图床上传图片
- 在线配置编辑
- 在线文章管理
- 在线页面管理
- 较为完善的缓存功能
- Webhook 清除缓存
- 自动检查更新
- 实验性的在线更新
- 自动填充date模板

## 如何部署
### 申请 MongoDB 
[注册 MongoDB 账号](https://www.mongodb.com/cloud/atlas/register) 创建免费 MongoDB 数据库，区域推荐选择 AWS / N. 
  Virginia (us-east-1) 在 Clusters 页面点击 CONNECT，按步骤设置允许所有 IP 地址的连接），创建数据库用户，并记录数据库连接信息，密码即为你所设置的值
![](https://user-images.githubusercontent.com/51912589/140946317-bafeac24-fe3f-408b-927a-ca9a88168fa8.png)
### Fork 本项目
打开 [项目主页](https://github.com/am-abudu/Qexo) 点击 Fork 将项目复刻到您的账户下
### 创建 Vercel 项目
打开 [Vercel](https://vercel.com) 注册账号并绑定 Github 新建一个项目并绑定 Fork 的仓库
### 部署
在项目部署界面添加环境变量 Environment Variables
| 名称 | 意义 | 示例 |
| --- | --- | --- |
| DOMAINS | 你所允许通信的安全域名 注意双引号 | [".vercel.app", "127.0.0.1", ".yoursite.com"] |
| MONGODB_HOST | MongoDB 连接地址 | mongodb+srv://cluster0.xxxx.mongodb.net |
| MONGODB_PORT | MongoDB 通信端口 默认应填写 27017 | 27017 |
| MONGODB_USER | MongoDB 用户名 | abudu |
| MONGODB_DB | MongoDB 数据库名 | Cluster0 |
| MONGODB_PASS | MongoDB 密码 | JWo0xxxxxxxx |

点击 Deploy 开始部署，若没有 Error 信息即可打开域名进入初始化引导
## 鸣谢
- [Ace](https://ace.c9.io/)
- [Argon-Dashboard-Django](https://github.com/creativetimofficial/argon-dashboard-django)
- [Bootstrap](https://getbootstrap.com/)
- [Bootstrap-Notify](https://github.com/mouse0270/bootstrap-notify)
- [Django](https://github.com/django/django)
- [Djongo](https://github.com/nesdis/djongo)
- [HexoPlusPlus](https://github.com/HexoPlusPlus/HexoPlusPlus)
- [jQuery](https://jquery.com/)
- [Vercel-Python-WSGI](https://github.com/ardnt/vercel-python-wsgi)
`

**Comment by Fgaoxing** [comment]
部署按钮
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://vercel.com/new/clone?s=https://github.com/am-abudu/Qexo)

**Comment by Fgaoxing** [comment]
一个域名好用，另一个不好用[不好用](https://admin.yt-blog.top/)[好用](https://qexo.yt-blog.top/)
