### ISSUE TITLE
openAPI

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#25]
加入api支持,使用qexo网站/api，基本的增删改查以及小工具，参数如下（我想的）

**Comment by Fgaoxing** [comment]
增加文章：/api/add/?name=用户名&password=密码&word_name=文件名&文章内容

**Comment by Fgaoxing** [comment]
增加文章：/api/add/？name=用户名&password=密码&word_name=文件名&word=文章内容

**Comment by Fgaoxing** [comment]
增加页面：/api/add/？name=用户名&password=密码&page_name=文件名&page=页面内容

**Comment by am-abudu** [comment]
Api已经在1.4.4支持，最近将写入文档

**Comment by Fgaoxing** [comment]
别忘了，api用后在通知中提醒
![image](https://user-images.githubusercontent.com/92655031/147258590-424711dd-e737-4769-8755-6f2643122bb2.png)
