### ISSUE TITLE
建议 or 问题

### ISSUE THREAD

**Issue by leafmoes** [am-abudu/Qexo#28]
1. 更新以前文章没有给加上更新时间
2. 生成文章的时候可不可以自动生成abbrlink之类的东西（当然，也就使用这个插件的用户需要,<del>如果有什么更好的生成永久链接的方法请告诉我</del>
3. 能不能支持cdn引入表情，微软的那个属实有点少、
4. 引用的vditor可以添加 切换编辑模式功能 嘛，我挺喜欢即时渲染的，虽然<del>Ctrl+Alt+8</del>可以切换。还有就是要是添加了这个按钮，希望可以设置默认编辑模式/狗头护体
5. 暂时想到这些，想到其他再提。

**Comment by leafmoes** [comment]
对了，新建文章时vditor里面的内容默认值修改功能

**Comment by am-abudu** [comment]
1. 已列入todo
2. 生成这个有更棒的办法，即在github action进行处理
3. 已加入todo，但vditor的json与owo不同，有特殊的写法
4. todo 将会放在右上角
5. 默认值支持{{time}}关键字 需要在scaffold里面编辑 参考hexo文档

**Comment by leafmoes** [comment]
<del>我又来提建议了</del>
自定义页面增加对其子页面的编辑功能/狗头护体

**Comment by Fgaoxing** [comment]
最好支持全部vditor功能
