### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by leafmoes** [am-abudu/Qexo#30]
希望支持把图片上传到`source/img/`
图片存放在网上的图床（free）容易挂，<del>都用hexo了，还能用得起付费服务嘛(好吧，主要我7bu账号不知道为什么被冻结了，好像好久没登录，现在账号还要买了居然)</del>

> 图片上传通过md5生成新的文件名（避免中文名称太过难看
> 仅使用Vditor上传时会自动生成
图片页面添加上传图片功能

**Comment by am-abudu** [comment]
若上传到Git仓库 那么应使用什么链接进行访问？

**Comment by leafmoes** [comment]
那可以换成npm+unpkg嘛，文件先上传到git仓库，然后ation提交到npm，再用unpkg国内镜像访问(狗头

**Comment by leafmoes** [comment]
不知道这违反TOS嘛😂

**Comment by am-abudu** [comment]
程序为amazon s3提供了支持，建议使用b2存储

**Comment by leafmoes** [comment]
好吧，我去研究一下，以前没用过
