### ISSUE TITLE
多语言-国际化（i18n）

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#34]
请务必支持,在设置里设置语言后,文章保存，自动翻译:https://zhuanlan.zhihu.com/p/81945858 ，按照https://hexo.io/zh-cn/docs/internationalization.html 存放。再开头结尾加入切换按钮。
---
中文  English
---
注意：代码不翻译！
                                                                                                                                                   ———   懵懂的初一少年
                                                                                                                                                                  https://yt-blgo.top
                                                                                                                                                                       已加友链

**Comment by am-abudu** [comment]
并没能理解你的意思
Hexo官方文档中的国际化(i18n)似乎指的是站点主题的国际化
翻译API给出的翻译相当不好，建议自己翻译，且在编辑器集成这个功能实用性不强且没有先例

**Comment by Fgaoxing** [comment]
是在Qexo设置中添加语言，文章翻译好复制到语言名的文件夹内，以支持国际化
