### ISSUE TITLE
部署出现错误

### ISSUE THREAD

**Issue by HideInMatrix** [am-abudu/Qexo#360]
### Qexo 版本

v2.7.0

### 平台

 PlanetScale&vercel

### 问题描述

![image](https://user-images.githubusercontent.com/99717719/232399344-b7dc4af3-81c9-451a-b447-7e5a51b77e84.png)

### 截图

![image](https://user-images.githubusercontent.com/99717719/232399439-9ae9dbcb-909b-4038-b4d7-5fd1e96b2d4d.png)

**Comment by am-abudu** [comment]
请检查数据库信息

**Comment by HideInMatrix** [comment]
> 请检查数据库信息

数据库检查了，本地用Navicat可以连接上去。不知道Qexo对PlanetScale的格式是不是教程写的那样

**Comment by am-abudu** [comment]
可以先尝试使用别的数据库

**Comment by Jeamorg** [comment]
Planetscale 数据库这样填可以部署成功

![Snipaste_2023-07-07_22-06-32](https://github.com/Qexo/Qexo/assets/93057377/e965f30f-2271-4e59-abcf-0cd84eaed076)
