### ISSUE TITLE
邮箱推送

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#42]
将通知同时推送到邮箱，发布或更新文章时推送到读者，代替谷歌，请制作页面供读者输入邮箱。你也遇到了这个问题吧，谷歌不能用！

**Comment by Fgaoxing** [comment]
注：发送与接收可以不一样

**Comment by am-abudu** [comment]
因为这些功能与编辑器有一定距离 可能会开一个新的项目

**Comment by Fgaoxing** [comment]
希望QEXO超过hpp

**Comment by am-abudu** [comment]
> 希望QEXO超过hpp

共同促进，相互学习
