### ISSUE TITLE
友链管理器和前端友情链接

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#46]
一键管理友链申请和友链页面

**Comment by Fgaoxing** [comment]
<div class="notes_card">
                <a target="_blank" rel="nofollow" href="https://talk.tutime.cn/">
                <div class="card-img" style="background-image: url(https://image.thum.io/get/width/1024/crop/768/https://www.yt-blog.top);"></div>
                </a><div class="card-u"><a target="_blank" rel="nofollow" href="https://www.yt-blog.top">
                    <div class="card-u-a">
                    <img class="card-u-avatar" src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg" onerror="this.onerror=null; this.src=this.srcset='https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg'" srcset="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg">
                    </div>
                    </a><div class="card-u-t"><a target="_blank" rel="nofollow" href="https://www.yt-blog.top">
                    </a><p class="card-u-t-text"><a target="_blank" rel="nofollow" href="https://www.yt-blog.top">
                        <b class="card-u-t-title">名称</b><br>
                        </a><a class="card-u-t-text">简介</a>
                    </p>
                    </div>
                </div>
                
            </div>

**Comment by Fgaoxing** [comment]
https://github.com/ye-tutu/Make_Links

**Comment by Fgaoxing** [comment]
友链页作为文章，使用嵌入方法

**Comment by Fgaoxing** [comment]
背景在Css里!

**Comment by Fgaoxing** [comment]
https://www.thum.io/

**Comment by qystudio0** [comment]
顺便支持一下vlts官方5.0的友链模式
https://github.com/qystudio0/friends
在qexo里给issue打标签就可以了

**Comment by am-abudu** [comment]
> 顺便支持一下vlts官方5.0的友链模式 https://github.com/qystudio0/friends 在qexo里给issue打标签就可以了

我不希望需要另外的适配 而是类似HPP Talk的嵌入方式

**Comment by Fgaoxing** [comment]
可以直接由Qexo创建页面并嵌入，无需用户操作，Qexo自动进行配置！

**Comment by Fgaoxing** [comment]
这是Qexo的优势，可以编辑页面，只要用户指定页面即可！

**Comment by Fgaoxing** [comment]
希望在1.5.x上线该功能！

**Comment by qystudio0** [comment]
这种功能不能由用户主动申请，是博主去添加比较麻烦，希望qexo可以解决这个弊端

**Comment by am-abudu** [comment]
> 这种功能不能由用户主动申请，是博主去添加比较麻烦，希望qexo可以解决这个弊端

这肯定是可以由API实现的，但第一个版本预计不会推出这个功能，而是单一的友链管理

**Comment by qystudio0** [comment]
但是可以学习vlts的动态友链，利用issue作为用户申请，action自动生成json，网站方面用api调用就可以了

**Comment by qystudio0** [comment]
可以看看xaoxuu大佬的https://github.com/xaoxuu/issues-api

**Comment by am-abudu** [comment]
> 

与我的想法类似 但是Qexo为动态部署提供了可能性，所以我会选择将数据存储在数据库中，静待Dev分支的下一次推送...

**Comment by Fgaoxing** [comment]
在友链底部直接申请或跳转至Qexo申请，然后在管理页显示即可。自动检测是否可以访问，有没有https，备案信息等！

**Comment by Fgaoxing** [comment]
我是这么想的，Github issue有时不好访问

**Comment by Fgaoxing** [comment]
好多人用萌备，所以萌备也得算，不过只显示萌备号而已

**Comment by Fgaoxing** [comment]
当然其实可以两个一起上

**Comment by Fgaoxing** [comment]
申请时注意要加邮箱，申请结果将发送至申请人邮箱

**Comment by Fgaoxing** [comment]
@am-abudu 邮箱我注册了，密码别改，Qexo2021@outlook.com，密码发你邮箱上了

**Comment by Fgaoxing** [comment]
在有人申请时向博主发送邮件，并在Qexo中通知！

**Comment by Fgaoxing** [comment]
https://blog.csdn.net/u010413052/article/details/79875149

**Comment by Fgaoxing** [comment]
dev分支注销按钮没了！

**Comment by am-abudu** [comment]
> dev分支注销按钮没了！

注销按键请使用右上角用户栏

**Comment by am-abudu** [comment]
在1.5.1中基本实现
