### ISSUE TITLE
校验失败

### ISSUE THREAD

**Issue by ooahz** [am-abudu/Qexo#52]
一直校验失败
![Hexo管理面板 - 初始化 - Google Chrome 2022_1_19 21_50_40](https://user-images.githubusercontent.com/57132258/150143797-32eb086a-311a-40b9-bccf-c27ecba04bb6.png)

**Comment by am-abudu** [comment]
https://github.com/am-abudu/Qexo/wiki/Github-%E9%85%8D%E7%BD%AE
请仔细阅读wiki查看配置说明
