### ISSUE TITLE
waline、valine、minivaline评论管理

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#59]
- [ 加入waline评论管理] 
- [ 加入valine评论管理] 
- [ 加入minivaline评论管理]
这些是主流评论

**Comment by Fgaoxing** [comment]
请不要关闭谢谢

**Comment by am-abudu** [comment]
例如waline/twikoo都有官方支持的管理系统，而类似的评论系统有很多，若支持会导致程序过于臃肿，这不是我想看到的

**Comment by Fgaoxing** [comment]
10042好像加了twikoo的函数  #56

**Comment by Fgaoxing** [comment]
你可以改为插件，使用哪个下载那个

**Comment by Fgaoxing** [comment]
若切换评论这回更换插件，增加Qexo的延展性

**Comment by Fgaoxing** [comment]
类似于更新，只是获取的是库的一部分，也可以是一个分支

**Comment by am-abudu** [comment]
但是Vercel仅这样做每次都需要进行重新部署，这有点麻烦

**Comment by Fgaoxing** [comment]
重新部署后自动清除缓存，这样在部署的时候，仍然以使用，只有刷新才会展示新页面，出评论外，还可以有很多插件

**Comment by qystudio0** [comment]
可以折中的支持另一种方法，以引入页面的形式，由qexo自动登录
> https://github.com/YunYouJun/kotodama

**Comment by Fgaoxing** [comment]
> 可以折中的支持另一种方法，以引入页面的形式，由qexo自动登录
> 
> > https://github.com/YunYouJun/kotodama

我并不支持，会影响兼容性，架构不同，没办法放到一起

**Comment by qystudio0** [comment]
> > 可以折中的支持另一种方法，以引入页面的形式，由qexo自动登录
> > > https://github.com/YunYouJun/kotodama
> 
> 我并不支持，会影响兼容性，架构不同，没办法放到一起
不同评论可以使用不同插件，如waline disscuz可以引入页面，twikoo valine可以用API

**Comment by Fgaoxing** [comment]
我说的是和Qexo嵌入问题，最好都用python

**Comment by am-abudu** [comment]
> > > 可以折中的支持另一种方法，以引入页面的形式，由qexo自动登录
> > > > https://github.com/YunYouJun/kotodama
> > 
> > 
> > 我并不支持，会影响兼容性，架构不同，没办法放到一起
> 
> 不同评论可以使用不同插件，如waline discuss可以引入页面，twikoo valine可以用API

这样就失去意义了吧，因为直接用原生的管理器显然更好

**Comment by qystudio0** [comment]
切换挺麻烦的，如果可以在qexo一站完成不是更方便吗

**Comment by am-abudu** [comment]
> 切换挺麻烦的，如果可以在qexo一站完成不是更方便吗

哈哈 但我觉得达成的效果并不会很好 还有一些跨站的小问题 先搁置吧
