### ISSUE TITLE
小白配置问题 请问这种报错是哪里出了问题

### ISSUE THREAD

**Issue by juxiaoshuai** [am-abudu/Qexo#63]
如图
![image](https://user-images.githubusercontent.com/64566402/151394691-a243508d-c03c-4cb9-a039-5ae998141ee5.png)

**Comment by am-abudu** [comment]
数据库信息错误 参考文档 [Vercel 部署](https://github.com/am-abudu/Qexo/wiki/Vercel-%E9%83%A8%E7%BD%B2)
