### ISSUE TITLE
更多的友链适配

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#70]
wiki主题中的[uskLSLrxpc41pwrhgvfDFXx](https://github.com/am-abudu/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#volantis)，第一个侧边栏，好像多打了个 **”**

**Comment by Fgaoxing** [comment]
我还适配了土土的那个link，代码在https://cdn.jsdelivr.net/gh/Fgaoxing/blog-cdn@main/source/js/tulinks.js，嵌入代码是这个稍等

**Comment by Fgaoxing** [comment]
```html
<div id="friends"></div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/qexo-static@1.0.7/hexo/friends/friends.css">
<script src="./tulink.js"></script>
<script>loadQexoFriends("friends", "https://admin.yt-blog.top")</script>
```
这个哪里都可以用！html由土土开发

**Comment by am-abudu** [comment]
> wiki主题中的[uskLSLrxpc41pwrhgvfDFXx](https://github.com/am-abudu/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#volantis)，第一个侧边栏，好像多打了个 **”**

没找着在哪一行

**Comment by am-abudu** [comment]
> ```
> <div id="friends"></div>
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/qexo-static@1.0.7/hexo/friends/friends.css">
> <script src="./tulink.js"></script>
> <script>loadQexoFriends("friends", "https://admin.yt-blog.top")</script>
> ```
> 
> 这个哪里都可以用！html由土土开发

请问这是侧边栏还是页面

**Comment by Fgaoxing** [comment]
> > ```
> > <div id="friends"></div>
> > <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/qexo-static@1.0.7/hexo/friends/friends.css">
> > <script src="./tulink.js"></script>
> > <script>loadQexoFriends("friends", "https://admin.yt-blog.top")</script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个哪里都可以用！html由土土开发
> 
> 请问这是侧边栏还是页面

页面

**Comment by Fgaoxing** [comment]
> > ```
> > <div id="friends"></div>
> > <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/qexo-static@1.0.7/hexo/friends/friends.css">
> > <script src="./tulink.js"></script>
> > <script>loadQexoFriends("friends", "https://admin.yt-blog.top")</script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个哪里都可以用！html由土土开发
> 
> 请问这是侧边栏还是页面

这个是https://github.com/ye-tutu/Make_Links，用于Tuhome的

**Comment by Fgaoxing** [comment]
> > wiki主题中的[uskLSLrxpc41pwrhgvfDFXx](https://github.com/am-abudu/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#volantis)，第一个侧边栏，好像多打了个 **"**
> 
> 没找着在哪一行

![image](https://user-images.githubusercontent.com/92655031/152096345-11704c2b-e87a-48ae-8335-6593b40c0ee8.png)
