### ISSUE TITLE
图床功能希望添加GitHub+jsDelivr图床

### ISSUE THREAD

**Issue by fengsiran** [am-abudu/Qexo#71]
个人认为github+jsd图床方案自主管控比别家API图床更自由更安全，能否加入图片上传到账号指定Github仓库并生成cdn.jsdelivr.net/gh/username/repo@branch/filename.png这样链接的功能？可以参考[这个](https://github.com/XPoet/picx)图床系统。有webp转换，哈希文件名，压缩功能就更好了，谢谢！

**Comment by am-abudu** [comment]
该功能违反Jsdelivr相关政策(TOS)，故不给予支持
