### ISSUE TITLE
> > wiki主题中的[uskLSLrxpc41pwrhgvfDFXx](https://github.com/am-abudu/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#volantis)，第一个侧边栏，好像多打了个 **"**

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#72]
> > wiki主题中的[uskLSLrxpc41pwrhgvfDFXx](https://github.com/am-abudu/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#volantis)，第一个侧边栏，好像多打了个 **"**
> 
> 没找着在哪一行

![image](https://user-images.githubusercontent.com/92655031/152096345-11704c2b-e87a-48ae-8335-6593b40c0ee8.png)

_Originally posted by @Fgaoxing in https://github.com/am-abudu/Qexo/issues/70#issuecomment-1027585372_

**Comment by am-abudu** [comment]
已修改
