### ISSUE TITLE
圖床設置

### ISSUE THREAD

**Issue by gaminglifex** [am-abudu/Qexo#74]
我嘗試在使用imgur來當圖床 但好像不太行 (圖1)
我按下一步也不能skip這個部分 無論按下一步/完成都陣出 (圖2)
請問有其他可行方案嗎?
![image](https://user-images.githubusercontent.com/72642816/152268777-191a6af5-30f1-437d-899a-e3ffbb112180.png)
![image](https://user-images.githubusercontent.com/72642816/152268964-2cc9c7b6-2e18-4c1f-87a8-fcff16000f1d.png)

**Comment by am-abudu** [comment]
我认为这是数据库连接的问题 请问您使用的是由MongoDB提供的免费数据库还是您自己的数据库?如果确认数据库链接没有问题可以尝试全部放空并点击完成按键，这一步没有设置校验，仅仅只是数据库读写

**Comment by gaminglifex** [comment]
謝謝你的回覆 我是根據你的推薦使用免費的mongoDB 我該如何測試mongoDB的連接? :))

**Comment by am-abudu** [comment]
是使用的AWS / N. Virginia (us-east-1)的免费数据库吗，如果不是建议改为如此
另:能进入此界面说明数据库连接无误，但连接时间可能过长

**Comment by gaminglifex** [comment]
謝謝你~ 確認是MongoDB伺服器位置的問題 至於使用imgur作圖床的設置仍是不行 :((

**Comment by am-abudu** [comment]
可以将配置截图 token打码 我来看一下配置

**Comment by gaminglifex** [comment]
![image](https://user-images.githubusercontent.com/72642816/152517956-10f4b0ed-b81b-4e65-a13b-2ae7fc9922f9.png)
謝謝你的回覆 這個imgur api我有使用過postman測試過可用 但就不太肯定如何設置在Qexo上
至於其他功能我仍未測試 如有問題我會再告訴你 💯 :))

**Comment by am-abudu** [comment]
你需要填写POST参数名 该项目为post中图片文件的key

**Comment by gaminglifex** [comment]
ooops 謝謝你 問題解決了
