### ISSUE TITLE
手机不显示用户名

### ISSUE THREAD

**Issue by Fgaoxing** [am-abudu/Qexo#81]
### Qexo 版本

1.5.3

### 问题描述

[bug]手机不显示用户名，所以无法退出

### 截图

![image](https://user-images.githubusercontent.com/92655031/152903215-4b838d0c-a07a-4f5c-afa4-d4d5e36fa2ef.png)

**Comment by am-abudu** [comment]
似乎是bug 因为用户名没有显示 但点击却有反馈

**Comment by am-abudu** [comment]
将在下一版本修复
